var e;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;Array.prototype.includes||(Array.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});Array.prototype.C||(Array.prototype.C=function(a){0>a&&(a+=this.length);return this[a]});NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);
"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edge/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");var u=Array.from,D=Array.prototype.includes,E=Function.call.bind(Array.prototype.slice),G=Function.apply.bind(Array.prototype.push),H=Function.call.bind(Array.prototype.forEach),I={16:!0,17:!0,18:!0,45:!0,46:!0},J=D.bind(["video","audio","object","embed"]),K=/(?!)/,L=/ *[$~]([<>{}&*+=@!#%:?^~-])(\d*) */,Q=window.self===window.top,R=window.origin||
document.origin||location.origin,S=location.hostname.toLowerCase().split(".").C(-2),T=S?RegExp("^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*"+S+"$","i"):K;function M(){browser.runtime.Ka?this.Y=browser.runtime.Ka(window):Q&&(this.Y=0);this.ba=[];this.Z=[];this.I=new Map;this.o={};this.Ha();window.__idm_connect__=this.Ha.bind(this,!0);this.b(1,window,"resize",this.Kb);this.b(1,window,"scroll",this.Lb);this.b(1,window,"blur",this.Cb);this.b(1,window,"keydown",this.Ra,!0);this.b(1,window,"keyup",this.Ra,
!0);this.b(1,window,"mousedown",this.Eb,!0);this.b(1,window,"mouseup",this.Gb,!0);this.b(1,window,"mousemove",this.Fb,!0);this.b(1,window,"click",this.Db,!0);this.b(1,document,"beforeload",this.Ab,!0);this.b(1,document,"DOMContentLoaded",this.Qa);"interactive"!=document.readyState&&"complete"!=document.readyState||this.Qa()}e=M.prototype;e.f=0;e.g=0;e.ea=-1;e.fa=-1;e.Xa=1;e.M=0;e.c="";e.Aa="";e.B="";e.Ca=K;e.Ga=K;e.R=K;e.m={};e.Da=K;e.Ea=K;e.Fa=K;e.qa=K;e.ka=":root:empty";e.na=":root:empty";e.O=":root:empty";
e.oa=":root:empty";e.ja=":root:empty";e.pa=":root:empty";e.ia=":root:empty";e.N=":root:empty";e.ma=0;e.la=K;e.sa=K;e.za=":root:empty";e.ta='$& div.xxzkxad $& section main[role="main"] $& div >div.x11aubdm:first-child < $& div >article <';e.wa='$& div.xxzkxad $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';e.ra='$+ article:scope $* main[role="main"] article';
e.va='$& div[role="dialog"] div[role="dialog"] >div $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';e.P="$* video";e.xa='$= poster ${ div[role="presentation"] >div >ul $<< $>:scope >div[data-instancekey] img $= src';e.ya="*.return.return.memoizedProps.videoFBID";e.ua=/\/(?:p|reel)\/([\w-]{11})(?:[/?#]|$)/;e.Ba=K;e.Ha=function(a){this.Ta(-1);this.a=a=browser.runtime.connect({name:(Q?"top":"sub")+(a?":retry":"")+("file:"==location.protocol?":file":"")});this.b(-1,
a,"onMessage",this.Ib);this.b(-1,a,"onDisconnect",this.Hb)};e.Hb=function(){browser.runtime.lastError;this.Ta();this.a=this.$=null;window.__idm_init__=!1;window.__idm_connect__=null};e.Ib=function(a){switch(a.shift()){case 11:this.kb.apply(this,a);break;case 17:this.lb.apply(this,a);break;case 12:this.mb.apply(this,a);break;case 13:this.cb=a.shift();break;case 14:this.pb.apply(this,a);break;case 15:this.qb.apply(this,a);break;case 16:this.rb.apply(this,a);break;case 18:this.ob.apply(this,a)}};e.Nb=
function(a,b){switch(this.J=a){case 1:this.s=this.eb=!0;if(a=b.shift())this.c=a;if(a=b.shift())this.Ca=RegExp(a);if(a=b.shift())this.R=RegExp(a);if(a=b.shift())this.m=a.split(/[|:]/).reduce(V,{});if(a=b.shift())this.Da=RegExp(a);if(a=b.shift())this.Ea=RegExp(a);if(a=b.shift())this.Fa=RegExp(a);if(a=b.shift())this.Ga=RegExp(a);break;case 2:this.s=!0;if(a=b.shift())this.c=a;if(a=b.shift())this.B=a;if(a=b.shift())this.qa=RegExp(a);if(a=b.shift())this.ka=a;if(a=b.shift())this.na=a;b.shift();if(a=b.shift())this.O=
a;if(a=b.shift())this.oa=a;if(a=b.shift())this.ja=a;if(a=b.shift())this.pa=a;if(a=b.shift())this.ia=a;if(a=b.shift())this.N=a;if(a=b.shift())this.ma=a;if(a=b.shift())this.Za=a;if(a=b.shift())this.la=RegExp(a);break;case 4:this.s=!0;if(a=b.shift())this.c=a;if(a=b.shift())this.Aa=a;if(a=b.shift())this.B=a;if(a=b.shift())this.sa=RegExp(a);if(a=b.shift())this.za=a;if(94>this.ab)break;if(a=b.shift())this.ta=a;if(a=b.shift())this.wa=a;if(a=b.shift())this.ra=a;if(a=b.shift())this.va=a;if(a=b.shift())this.P=
a;if(a=b.shift())this.xa=a;b.shift();if(a=b.shift())this.ya=a;if(a=b.shift())this.ua=RegExp(a);break;case 3:if(a=b.shift())this.Ba=RegExp(a);break;case 5:this.s=!0;if(a=b.shift())this.c=a;if(a=b.shift())this.B=a;if(a=b.shift())this.bb=a;break;default:this.s=!0;if(a=b.shift())this.c=a;if(a=b.shift())this.ha=a}this.c.includes("^/")&&((b=this.Aa)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=R.replaceAll(".","\\."),this.c=this.c.replaceAll("^/","^(?:"+b+")?/"))};e.W=function(a){if(this.J&&
this.K(arguments))switch(this.J){case 1:this.zb(a);break;case 2:this.vb(a);break;case 4:this.wb(a);break;case 3:this.yb(a);break;case 5:this.xb(a)}};e.U=function(a){var b=this.a,c;for(c of document.getElementsByTagName("script"))!c.src&&a.test(c.innerText)&&b.postMessage([34,null,-1,c.outerHTML]);b.postMessage([34,this.v()])};e.Sa=function(a,b,c){if(this.Ya&&b){var d=this.u(a);if(d){this.I.set(a,c);window.postMessage([1229212980,d,b],"/");return}}c(a)};e.Jb=function(a,b){if(a=this.o[a]){var c=this.I.get(a);
c&&(this.I.delete(a),c(a,b))}};e.Mb=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==R)switch(b[0]){case 1229212977:window.postMessage([1229212978,this.$,this.s,this.eb,this.c,this.B],"/");this.Ya=!0;break;case 1229212979:this.a.postMessage([36,b[1],b[2]]);break;case 1229212981:this.Jb(b[1],b[2])}};e.V=function(){var a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};e.u=function(a){var b=a.i;b||(b=a.i=this.$<<13|this.Xa++,a.setAttribute("__idm_id__",
b),this.o[b]=a);return b};e.F=function(a){a.l&&(window.clearTimeout(a.l),a.l=null);a.j&&(a.j.disconnect(),a.j=null);this.h&&this.h.unobserve(a);this.G&&this.G.unobserve(a);delete this.o[a.i]};e.S=function(a,b,c,d){if(!a.A){var f=this.u(a);f&&(b||c)&&(a.A=c||b,a.j||(a.j=new MutationObserver(this.L.bind(this)),a.j.observe(a,{attributes:!0,attributeFilter:["style"]})),this.h&&this.h.observe(a),this.G&&d&&this.G.observe(a),d=this.H(a),this.a.postMessage([41,f,a.localName,a.src||a.data,b,c,d]))}};e.jb=
function(a,b,c,d,f){var h,m,k,p,l=window.getComputedStyle.bind(window);try{var g=0;var q=document.activeElement;q&&J(q.localName)||(q=document.elementFromPoint(this.ea,this.fa))&&!J(q.localName)&&(q=null);for(var n of document.querySelectorAll("video,audio,object,embed")){var r=n.localName,t,w="object"==r||"embed"==r;if(w){var z=n.type.toLowerCase();if(z.startsWith("text/")||z.startsWith("image/"))continue;if("embed"==r&&"application/x-shockwave-flash"!=z)continue}if(f&&n.A==f&&(h=n))break;if(t=n.src||
n.data)t!=a&&t!=b||(h=n);else if(!w)for(var y of n.getElementsByTagName("source"))if((t=y.src)&&(t==a||t==b)&&(h=n))break;if(h)if("cover"==l(n).objectFit){var A=n;h=null}else break;if(!(A||q||m)){if(t){if((t==c||t==d)&&(m=n))continue;if("video"==r&&t.startsWith("data:audio/"))continue}var x=n.clientWidth,B=n.clientHeight;if(x&&B){var N=n.getBoundingClientRect();if(!(0>=N.right+window.scrollX||0>=N.bottom+window.scrollY))if("hidden"==l(n).visibility)"video"==r&&(p||(p=n));else{w=x*B;if(g<w&&1.35*x>
B&&x<3*B){g=w;var W=n}k||(k=n)}}}}}catch(X){}(n=h||A||q||m)?"video"!=n.localName&&"hidden"==l(n).visibility&&(n=null):n=W||k||p;n&&("embed"!=n.localName||n.clientWidth||n.clientHeight||(a=n.parentElement,"object"==a.localName&&(n=a)),this.u(n)?(a=n.j=new MutationObserver(this.L.bind(this)),a.observe(n,{attributes:!0,attributeFilter:["style"]}),a.observe(n.parentNode,{childList:!0}),this.h&&this.h.observe(n)):n=null);return n};e.ib=function(a,b,c){var d=null,f,h=browser.runtime.Ka,m;for(m of document.getElementsByTagName("iframe")){var k=
m.Ma;null==k&&h&&(k=m.Ma=h(m));if(k==a){d=m;break}else d||!(f=m.src)||f!=b&&f!=c||(d=m)}return d&&this.u(d)};e.H=function(a){var b=null;try{var c=window.getComputedStyle(a),d=a.getBoundingClientRect(),f=this.M,h=Math.round(d.width),m=Math.round(d.height);if("hidden"==c.visibility||0==c.opacity||a.sb)return h>5*m?null:!1;if(1==this.J&&0==a.offsetTop+a.offsetHeight){for(var k=a;k=k.parentElement;){var p=window.getComputedStyle(k);if("block"!=p.display)break;if(0==p.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();
f=0}var l=Math.round(d.left)+a.clientLeft,g=Math.round(d.top)+a.clientTop,q=d=0;k=a;p=c;for(var n,r;f--&&"block"==p.display&&(n=k.parentElement)&&"div"==n.localName;k=n,p=r){r=window.getComputedStyle(n);d-=k.offsetLeft;q-=k.offsetTop;if("hidden"==r.overflowX){var t=h-n.offsetWidth-d;0<d&&(h-=d,l+=d);0<t&&(h-=t);f=0}if("hidden"==r.overflowY){var w=m-n.offsetHeight-q;0<q&&(m-=q,g+=q);0<w&&(m-=w);f=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.A||1>a.readyState&&2==a.networkState)&&
(b=!1);if(15>h||10>m)return b;break;case "audio":if(1>h&&1>m)return b;var z=!0}var y=document.documentElement,A=y.scrollWidth||y.clientWidth,x=y.scrollHeight||y.clientHeight;if(l>=A||g>=x||z&&!l&&!g)return b;0==l&&g==-x&&h==A&&m==x&&(g=0);b=[l,g,l+h,g+m,this.V()]}catch(B){}return b};e.v=function(){var a=Q?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g,
" "),b=new String(b.trim()),b.src=a);return b};e.nb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement,b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0),d=0,f=0,h=0,m;for(m of c)if(m.offsetWidth>=b){var k=window.getComputedStyle(m);.95<=k.opacity&&(c=k.zIndex,"fixed"==k.position?(k=m.offsetHeight+m.offsetTop,d<k&&k<a&&(d=k,f=c)):h<c&&(h=c))}f<h&&(d=0);return d};e.kb=function(a,b,c,d,f,h,m,k,p){k&&O("text/javascript",
k);this.ab=a;this.$=b;if(d){this.Y=d;try{window.frameElement&&(window.frameElement.Ma=d)}catch(l){}}this.La(h);f&&this.Nb(f,E(arguments,9));p&&(this.b(2,window,"message",this.Mb),O("text/javascript",p));"loading"==document.readyState?this.ca=!0:this.W()};e.lb=function(a){this.da&&this.f&&(this.f=0,this.ga=window.setTimeout(this.aa.bind(this,!1),3E3));this.W(!0);a&&this.La()};e.La=function(a){if(this.K(arguments)){var b=[21,this.Pb||location.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,
document.getElementsByTagName("audio").length);this.a.postMessage(b)}};e.pb=function(a){var b=a?this.K(arguments):1;if(0<b||0>b&&1!=this.J){b=this.v();var c=this.V(),d=this.nb();this.a.postMessage([24,b,b&&b.src,c,d])}};e.rb=function(a,b,c,d,f){c||(c=this.ib(b,d,f));d=(d=c&&this.o[c])&&this.H(d);this.a.postMessage([22,a,b,c,d])};e.ob=function(a,b){var c=document.getElementsByTagName("a"),d;for(d of c)try{if(d.href==b){var f=d.download||null;var h=d.innerText.trim()||d.title||null;break}}catch(m){}this.a.postMessage([35,
a,f,h])};e.qb=function(a,b,c,d,f,h,m){if(this.K(arguments)){var k=[23,a,b,!1],p,l,g;if(b)b&&((p=this.o[b])||(k[3]=!0));else{if(p=this.jb(c,d,f,h,m)){if(this.ha&&(l=v(p,this.ha)))var q=200;else if(l=p.getAttribute("operadetachedviewtitle"))q=130;k[2]=b=p.i;k[5]=p.localName;k[6]=p.src||p.data}!l&&(l=this.v())&&(q=l.src,(g=T.exec(l))&&(l=g[1]));k[7]=l;k[8]=q}p&&(l=this.H(p),null!=l||document.contains(p)?k[4]=l:(this.F(p),k[3]=!0));this.a.postMessage(k)}};e.mb=function(a,b,c,d){var f=d?RegExp(d,"i"):
null;d=this.Ja(document,f,b);var h=document.getElementsByTagName("iframe"),m;for(m of h)try{var k=m.contentDocument;k&&!m.src&&G(d,this.Ja(k,f,b))}catch(p){}a=[27,a,this.Y,d.length];c||(a[4]=d,a[5]=location.href,Q&&(a[6]=location.href,a[7]=document.title));this.a.postMessage(a)};e.Ja=function(a,b,c){var d=[],f={},h="",m="",k=!c;if(c){var p=a.getSelection();if(!p||p.isCollapsed&&!p.toString().trim())return d}for(var l of a.getElementsByTagName("a"))if(k||p.containsNode(l,!0))try{var g=l.href;g&&!f[g]&&
b.test(g)&&(f[g]=d.push([g,2,l.download||null,l.innerText.trim()||l.title]));c&&f[g]&&(m+=l.innerText,m+="\n")}catch(n){}for(l of a.getElementsByTagName("area"))if(k||p.containsNode(l,!0))try{(g=l.href)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,2,null,l.alt]))}catch(n){}for(l of a.getElementsByTagName("img"))if(k||p.containsNode(l,!0))try{(g=l.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+l.alt])),k&&l.onclick&&(h+=l.onclick,h+="\n")}catch(n){}if(c){if(h=p.toString()){c=this.D(m);
for(g of this.D(h))g&&!f[g]&&b.test(g)&&!c.includes(g)&&(f[g]=d.push([g,1]))}for(l of a.getElementsByTagName("textarea"))if(a=l.selectionStart,h=l.selectionEnd,(c=p.isCollapsed&&a<h)||p.containsNode(l,!0))try{var q=c?l.value.substring(a,h):l.value;for(g of this.D(q))g&&!f[g]&&b.test(g)&&(f[g]=d.push([g,1]))}catch(n){}}else{for(l of a.getElementsByTagName("iframe"))try{(g=l.src)&&!f[g]&&b.test(g)&&(f[g]=d.push([g,4]))}catch(n){}for(l of a.getElementsByTagName("script"))h+=l.innerText,h+="\n";if(h)for(g of this.D(h))g&&
!f[g]&&b.test(g)&&(f[g]=d.push([g,5]))}return d};e.D=function(a){if(!this.Wa){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\-\u00a0-\ufeff","%T":"\\w\\-.+*()$!,%\u00a0-\ufeff","%Q":"^\\s\\[\\]{}()"}));this.Wa=RegExp(b,"gi")}for(var c=[];b=this.Wa.exec(a);)c.push(b.shift());return c};e.K=function(a){var b=this.f;b||(a=u(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),
this.Z.push(a));return b};e.Qa=function(a){try{var b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.f=a&&b?-1:1;b&&(a=this.da,a||(this.da=a=new MutationObserver(this.aa.bind(this))),a.observe(b,{childList:!0}));try{this.h=new ResizeObserver(this.L.bind(this))}catch(c){}try{this.G=new IntersectionObserver(this.L.bind(this),{threshold:.2})}catch(c){}this.ca&&(this.ca=!1,this.W());for(a=this.Z;b=a.shift();)b.shift().apply(this,b)};e.L=function(a){if(this.a)for(var b of a)a=b.target,
a.i&&(document.contains(a)?(null!=b.isIntersecting&&(a.sb=!b.isIntersecting),a.l&&window.clearTimeout(a.l),a.l=window.setTimeout(this.Bb.bind(this,a),200)):(this.a.postMessage([23,null,a.i,!0]),this.F(a)))};e.Bb=function(a){if(!this.a)return this.F(a);a.l=null;var b=document.contains(a),c;b?c=this.H(a):this.F(a);this.a.postMessage([23,null,a.i,!b,c])};e.aa=function(a){if(a)window.clearTimeout(this.ga),this.ga=window.setTimeout(this.aa.bind(this,!1),1E3);else{0>this.f?this.f=1:++this.f;for(var b=this.Z;a=
b.shift();)a.shift().apply(this,a)}};e.Ab=function(a){var b=a.target,c=b.localName;J(c)&&a.url&&(b=this.u(b),this.a.postMessage([25,b,c,a.url]))};e.Ra=function(a){!a.repeat&&I[a.keyCode]&&this.a.postMessage([31,a.keyCode,"keydown"==a.type])};e.Eb=function(a){this.cb&&this.a.postMessage([28]);if(0==a.button){var b=a.view.getSelection();b&&b.isCollapsed&&!b.toString().trim()&&(this.g=1);this.a.postMessage([32,a.button,!0])}};e.Gb=function(a){if(0==a.button){this.ea=a.clientX;this.fa=a.clientY;this.a.postMessage([32,
a.button,!1]);var b=a.view.getSelection();b&&this.g&&(this.g=b.isCollapsed&&!b.toString().trim()?0:2)&&this.a.postMessage([26,a.clientX,a.clientY,this.V()])}};e.Fb=function(){2==this.g&&(this.g=0)};e.Db=function(a){a=a.target;"a"==a.localName&&this.a.postMessage([39,a.hasAttribute("download"),a.href,a.download])};e.Lb=function(){this.a.postMessage([29])};e.Kb=function(a){a=a.target;this.a.postMessage([30,a.innerWidth,a.innerHeight])};e.Cb=function(){this.g=0;this.a.postMessage([33])};e.b=function(a,
b,c,d,f){var h=u(arguments);h[3]=d.bind(this);this.ba.push(h);0>a?(b=b[c],b.addListener.apply(b,h.slice(3))):b.addEventListener.apply(b,h.slice(2))};e.Ta=function(a){for(var b=this.ba,c=0;c<b.length;c++){var d=b[c][0];if(!a||a==d){var f=b.splice(c--,1).pop(),h=f.splice(0,2).pop();0>d?(h=h[f.shift()],h.removeListener.apply(h,f)):h.removeEventListener.apply(h,f)}}};e.zb=function(a){if(!a){a=this.a;var b,c,d,f,h=0;for(k of document.getElementsByTagName("script")){if(k.src){if(f=this.R.exec(k.src))h|=
1,this.m[f[1]]?c=f[1]:b=k.src}else if(f=this.Ga.exec(k.innerText))h|=2,this.m[f[1]]&&(d=parseInt(f[1],10));else if(this.Ca.test(k.innerText)){h|=4;var m=k.outerHTML}if(7==h)break}if(d||c){var k={};k[118]=d;k[124]=c;a.postMessage([37,1,2,k])}a.postMessage([34,this.v(),null,m]);b&&(m=new XMLHttpRequest,m.responseType="text",m.timeout=1E4,m.onreadystatechange=this.Ob.bind(this,b,m),m.open("GET",b,!0),m.send());this.M=2}};e.Ob=function(a,b){if(4==b.readyState){var c=this.R.exec(a);if((a=(a=this.Da.exec(b.response))&&
parseInt(a[1]||a[2],10))&&(!this.m[a]||!this.m[c[1]])){var d=this.Ea.exec(b.response);b=this.Fa.exec(b.response);if(d&&b&&d[2]==b[1]){c=c&&c[1];var f={};f[118]=a;f[119]=d[0];f[120]=b[0];f[124]=c;this.a.postMessage([37,1,1,f])}}}};e.vb=function d(b,c){b?(c&&b.shift().disconnect(),this.X.disconnect(),this.Va.disconnect(),this.Ua.clear()):(this.U(this.qa),this.X=new MutationObserver(this.gb.bind(this)),this.Va=new MutationObserver(this.fb.bind(this)),this.Ua=new Set,this.M=3);if(c=this.$a=document.querySelector(this.na)){if(b=
this.X,b.observe(c,{childList:!0}),!this.Ia(c,!0)&&(c=c.querySelector(this.oa))){var f=C(c,this.O);f&&b.observe(c,{childList:!0});b.observe(f||c.parentNode,{childList:!0})}}else!b&&(c=document.querySelector(this.ka))&&(f=new MutationObserver(d.bind(this,b=[])),b.push(f),f.observe(c,{childList:!0}))};e.Ia=function(b,c){var d=this.X,f=this.O,h=this.ja,m=this.Va,k=this.Ua,p=0,l;for(l of b.querySelectorAll(h))k.has(l)||l.querySelector(h)||(k.add(l),m.observe(l,{childList:!0,subtree:!0}),c&&(b=C(l,f))&&
(d.observe(b,{childList:!0}),p++),H(l.getElementsByTagName("video"),this.T.bind(this)));return p};e.gb=function(b){var c=this.$a,d;for(d of b){b=d.target.isSameNode(c);for(var f of d.addedNodes)1==f.nodeType&&this.Ia(f,b)}};e.fb=function(b){var c=this.I,d=this.N,f;for(f of b)for(var h of f.addedNodes)if(1==h.nodeType)if(b=h.getElementsByTagName("video"),b.length)H(b,this.T.bind(this));else for(var m of c){b=m.shift();var k=C(b,d);k&&k.contains(h)&&this.T(b)}};e.T=function(b){if(!b.A){var c=this.ia,
d=this.ma,f=D.bind(["div","span","a"]),h,m,k,p,l,g=C(b,this.N),q=g&&g.querySelector(":scope >"+c);for(d=q?0:d;d--&&g&&f(g.localName);g=g.parentNode){var n=g;if(q=C(g,c+":scope:first-child:only-of-type"))break;if((k=g.previousSibling)&&"div"==k.localName){m||(m=g.querySelector('div[role="slider"]'));1==(l=g.querySelectorAll(c)).length?q=l[0]:(p=g.nextSibling)&&1==(l=p.querySelectorAll("ul:scope "+c)).length?q=l[0]:m&&1<(l=k.querySelectorAll(c)).length&&(q=l[l.length-1]);break}}q?q=q.href:n&&1==(l=
n.querySelectorAll(this.pa)).length&&(q=l[0].href);1==document.getElementsByTagName("video").length&&(h=this.la.exec(location.href))&&(h=h[1]);h||q?this.S(b,h,q):this.Sa(b,this.Za,this.hb.bind(this))}};e.hb=function(b,c){c&&this.S(b,c)};e.wb=function(b){!b&&(this.U(this.sa),b=v(document,this.za))&&(F(b,this.ta,this.ub.bind(this)),F(b,this.wa,this.Pa.bind(this)),F(document.body,this.va,this.Pa.bind(this)))};e.ub=function(b){for(var c of v(b,this.ra,[]))H(v(c,this.P,[]),this.Oa.bind(this))};e.Pa=function(b){H(v(b,
this.P,[]),this.Oa.bind(this))};e.Na=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.ua.exec(location.href))&&(c=c[1]);this.S(b,c,d,!0)};e.Oa=function(b){if(!b.A){var c=v(b,this.xa);c?this.Na(b,null,c):this.Sa(b,this.ya,this.tb.bind(this))}};e.tb=function(b,c){c&&this.Na(b,c)};e.yb=function(b){b||this.U(this.Ba)};e.xb=function(b){if(!b){var c=v(document,this.bb);c&&(b=this.v(),c=c.outerHTML,this.a.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function O(b,c){var d=
b.startsWith("image/")?"img":"script";d=document.createElement(d);d.src="data:"+b+";base64,"+c;d.onload=d.remove.bind(d);document.documentElement.appendChild(d)}function v(b,c,d){function f(q,n,r){for(;r&&n--;)r=r.parentElement;r&&(isNaN(q)||this.push(q),this.push(r));return r}if(!c)return d;var h,m,k=!0,p=d||[],l=c.split(L);1==l.length?(l[0].startsWith("<")&&l.unshift(l.shift().slice(1)+"<"),l.unshift(">",NaN)):l.shift();for(;b&&(h=l.shift());){c=parseInt(l.shift(),10);var g=l.shift().trim();for(m=
1;"<"==g[g.length-m];m++);--m&&(g=g.slice(0,-m).trim());switch(h){case "<":b=P(g?b.closest(g):b,m);break;case ">":b=P(b.querySelector(g),m);break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "&":b=f.call(p,c,m,b.querySelector(g));k=!1;break;case "*":b.querySelectorAll(g).forEach(f.bind(p,c,m));k=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;f.call(p,c,m,g);k=!1;break;case "=":if(g=b.getAttribute(g))return g;k=!1;break;case "@":if(g=
b.textContent.trim())return g;k=!1}}return p.length?p:k&&b||d}function F(b,c,d,f,h,m){if(null==f){f=v(b,c,[]);m=new MutationObserver(F.bind(null,b,c,d,f));m.observe(b,{childList:!0});for(var k of f)m.observe(k,{childList:!0});f.length&&d(f.C(-1))}else for(var p of h){for(k of p.addedNodes)if(1==k.nodeType)if(h=v(b,c,[]).slice(f.length),h.length){G(f,h);for(var l of h)m.observe(l,{childList:!0});for(var g of h.pop().children)d(g)}else p.target.isSameNode(f.C(-1))&&d(k);for(k of p.removedNodes)if(1==
k.nodeType)for(h=0;h<f.length;h++)if(k.contains(f[h])){f.splice(h);break}}}function C(b,c){var d;for(d=0;"<"==c[d];d++);d&&(c=c.slice(d));for(b=b.closest(c);b&&d--;b=b.parentElement);return b}function P(b,c){for(;b&&c--;b=b.parentElement);return b}function V(b,c){c&&(b[c]=!0);return b}var U=Object.isExtensible;try{U(null)}catch(b){U=function(c){return c instanceof Object}}String.prototype.replaceAll||(String.prototype.replaceAll=function(b,c){return this.split(b).join(c)});new M}!0;
